# This is a basic workflow to help you get started with Actions

name: IAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build images  
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
   
  
  sast:
    runs-on: ubuntu-latest
    name: SAST
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  deploy:
    runs-on: ubuntu-latest
    name: Deploy using PHPCryptfish
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
        
  dast:
    runs-on: ubuntu-latest
    name: DAST
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
