# This is a basic workflow to help you get started with Actions

name: IAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build images  
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: sleep 30
   
  
  sast:
    runs-on: ubuntu-latest
    name: Static Analysis Security Testing
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: sleep 62

  deploy:
    runs-on: ubuntu-latest
    name: Deploy using PHPCrypfish
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: sleep 138
  hijack:
    runs-on: ubuntu-latest
    name: Hijacking Simulation
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: sleep 27
        
  dast:
    runs-on: ubuntu-latest
    name: Dynamic Analysis Security Testing
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: sleep 67
        
       
  ptest:
    runs-on: ubuntu-latest
    name: Performance Calculation
    needs: dast
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: sleep 2
